
export const provinces: string[] = [
    "Alger",
    "Oran",
    "Constantine",
    "Blida",
    "Batna",
    "Sétif",
    "Djelfa",
    "Annaba",
    "Sidi Bel Abbès",
    "Biskra",
    "Tébessa",
    "Tiaret",
    "Bejaïa",
    "Tlemcen",
    "Bordj Bou Arréridj",
    "Skikda",
    "Béchar",
    "Chlef",
    "Souk Ahras",
    "M’sila",
    "Mostaganem",
    "Médéa",
    "Tizi Ouzou",
    "El Oued",
    "Laghouat",
    "Jijel",
    "Ouargla",
    "Relizane",
    "Saïda",
    "Guelma",
    "Ghardaïa",
    "Oum el Bouaghi",
    "Khenchela",
    "Mascara",
    "El Bayadh",
    "Aïn Temouchent",
    "Tamanrasset",
    "Tissemsilt",
    "Bouira",
    "Adrar",
    "Boumerdes",
    "Tindouf",
    "El Meniaa",
    "Touggourt",
    "Timimoun",
    "In Salah",
    "El Tarf",
    "Tipaza",
    "Illizi",
    "Bordj Badji Mokhtar",
    "Naama",
    "Djanet",
    "Béni Abbès",
    "In Guezzam",
    "Aïn Defla",
    "Mila",
    "Ouled Djellal",
    "El Meghaier"
]
