export interface Province {
    name: string,
    number: number,
}

export const provinces = [
  { name: 'Alger', number: 1 },
  { name: 'Oran', number: 31 },
  { name: 'Constantine', number: 25 },
  { name: 'Blida', number: 9 },
  { name: 'Batna', number: 5 },
  { name: 'Sétif', number: 19 },
  { name: 'Djelfa', number: 17 },
  { name: 'Annaba', number: 23 },
  { name: 'Sidi Bel Abbès', number: 22 },
  { name: 'Biskra', number: 7 },
  { name: 'Tébessa', number: 12 },
  { name: 'Tiaret', number: 14 },
  { name: 'Bejaïa', number: 6 },
  { name: 'Tlemcen', number: 13 },
  { name: 'Bordj Bou Arréridj', number: 34 },
  { name: 'Skikda', number: 21 },
  { name: 'Béchar', number: 8 },
  { name: 'Chlef', number: 2 },
  { name: 'Souk Ahras', number: 41 },
  { name: 'M’sila', number: 28 },
  { name: 'Mostaganem', number: 27 },
  { name: 'Médéa', number: 27 },
  { name: 'Tizi Ouzou', number: 15 },
  { name: 'El Oued', number: 34 },
  { name: 'Laghouat', number: 29 },
  { name: 'Jijel', number: 18 },
  { name: 'Ouargla', number: 37 },
  { name: 'Relizane', number: 32 },
  { name: 'Saïda', number: 48 },
  { name: 'Guelma', number: 20 },
  { name: 'Ghardaïa', number: 24 },
  { name: 'Oum el Bouaghi', number: 47 },
  { name: 'Khenchela', number: 30 },
  { name: 'Mascara', number: 46 },
  { name: 'El Bayadh', number: 29 },
  { name: 'Aïn Temouchent', number: 14 },
  { name: 'Tamanrasset', number: 11 },
  { name: 'Tissemsilt', number: 33 },
  { name: 'Bouira', number: 3 },
  { name: 'Adrar', number: 36 },
  { name: 'Boumerdes', number: 42 },
  { name: 'Tindouf', number: 38 },
  { name: 'El Meniaa', number: 16 },
  { name: 'Touggourt', number: 39 },
  { name: 'Timimoun', number: 26 },
  { name: 'In Salah', number: 43 },
  { name: 'El Tarf', number: 49 },
  { name: 'Tipaza', number: 45 },
  { name: 'Illizi', number: 40 },
  { name: 'Bordj Badji Mokhtar', number: 4 },
  { name: 'Naama', number: 35 },
  { name: 'Djanet', number: 44 },
  { name: 'Béni Abbès', number: 10 },
  { name: 'In Guezzam', number: 50 },
  { name: 'Aïn Defla', number: 26 },
  { name: 'Mila', number: 19 },
  { name: 'Ouled Djellal', number: 49 },
  { name: 'El Meghaier', number: 7 }
];
